### ISSUE TITLE
Extend repository to include more shared configs

### ISSUE THREAD

**Issue by Gijsdeman** [GEWIS/js-configs#5]
### What would you like?

I would like to extend the repository to also include shared configs for other things than just `eslint`. For example `husky`, `releaserc` and `lintstaged`. If not for fully preset configs, at least a way to structurally extend a solid base.

### Why is this needed?

Brings more structure and simplicity to other repositories. Leads to a default being used for the whole organisation, and easy changes across the whole organisation.

**Comment by JustSamuel** [comment]
maybe we should rename the repo to configs then?

**Comment by Gijsdeman** [comment]
That would make sense yes. I can push a setup for the shared configs later as I mostly converted this locally already; I just have to check if Lerna actually works with our current setup (importing directly in other packages) or not.
